// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAEKZJIbP574eNX4DPnwY7lKJKjdErIh8',
    appId: '1:53648374508:web:d79571e55ba50f621483c9',
    messagingSenderId: '53648374508',
    projectId: 'park-me-project',
    authDomain: 'park-me-project.firebaseapp.com',
    storageBucket: 'park-me-project.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARwdsKHDQ9lwrLbO7pXC1L-MPuK2GO9DE',
    appId: '1:53648374508:android:299e8889f5bafafa1483c9',
    messagingSenderId: '53648374508',
    projectId: 'park-me-project',
    storageBucket: 'park-me-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRmeVq5VQqygaE5aE0pd1hBhXx22Z2WdM',
    appId: '1:53648374508:ios:f2befdb1282d490d1483c9',
    messagingSenderId: '53648374508',
    projectId: 'park-me-project',
    storageBucket: 'park-me-project.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRmeVq5VQqygaE5aE0pd1hBhXx22Z2WdM',
    appId: '1:53648374508:ios:f2befdb1282d490d1483c9',
    messagingSenderId: '53648374508',
    projectId: 'park-me-project',
    storageBucket: 'park-me-project.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBAEKZJIbP574eNX4DPnwY7lKJKjdErIh8',
    appId: '1:53648374508:web:3f218a7ac889e1a31483c9',
    messagingSenderId: '53648374508',
    projectId: 'park-me-project',
    authDomain: 'park-me-project.firebaseapp.com',
    storageBucket: 'park-me-project.firebasestorage.app',
  );
}
